# This is a basic workflow to help you get started with Actions

name: Cypress tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ cicd_workflow ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    env:
      REACT_APP_API_URL: ${{ secrets.API_URL }}
      CYPRESS_BASE_URL: 'http://localhost:3000'
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      HUBSPOT_APIKEY: ${{ secrets.HUBSPOT_APIKEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run 
        uses: cypress-io/github-action@v2
        with:
          start: npm run start-front

      
